### ISSUE TITLE
Unable to create AAC stream on Linux

### ISSUE THREAD

**Issue by tommaier123** [ManagedBass/ManagedBass#100]
Hello,
I am trying to play an AAC stream in my crossplatform application. On Windows it works fine but for Linux I need to load the AAC plugin.
Loading the plugin is successful but creating the stream fails with a FileFormat exception.
I'm pretty sure the stream is AAC but just in case I have tried loading all the available bass codec plugins.
On windows the stream channel type is listed as Media Foundation. But that doesn't mean it can't be AAC.
I have also tried using ManagedBass.Aac instead of loading the plugin but got a "undefined symbol: BASS_GetVersion" exception. This could be because I am using a single file executable.
Any ideas what I could be doing wrong?
Are there other ways to debug this issue?

**Comment by Beyley** [comment]
> Hello,
> I am trying to play an AAC stream in my crossplatform application. On Windows it works fine but for Linux I need to load the AAC plugin.
> Loading the plugin is successful but creating the stream fails with a FileFormat exception.
> I'm pretty sure the stream is AAC but just in case I have tried loading all the available bass codec plugins.
> On windows the stream channel type is listed as Media Foundation. But that doesn't mean it can't be AAC.
> I have also tried using ManagedBass.Aac instead of loading the plugin but got a "undefined symbol: BASS_GetVersion" exception. This could be because I am using a single file executable.
> Any ideas what I could be doing wrong?
> Are there other ways to debug this issue?

I recently had a similar issue, as it turns out it was because i was using an outdated Bass/BassAac

**Comment by DustinBond** [comment]
@tommaier123 did you get this all worked out? I'm assuming we can close this, please re-open if still an issue. But I'm playinga and AAC stream just fine.

**Comment by tommaier123** [comment]
Last time I tried it was not working but in the meantime I have changed some things. I'll try it again on linux and give you a minimal example if it doesn't work.
