### ISSUE TITLE
Cannot load libassflac.so plugin in Linux

### ISSUE THREAD

**Issue by mysteryx93** [ManagedBass/ManagedBass#107]
Trying to load plugins in Linux. The demo PluginTest works fine in Windows. Trying to load "libassflac.so" under Linux, however, always returns 0 with an error FileFormat. I'm able to load libassopus, but not libassflac. How can I make it work?

**Comment by mysteryx93** [comment]
Never mind. It's loading now. I honestly don't know what changed. Closing my case.

**Comment by DustinBond** [comment]
@mysteryx93 Usually if I get the Fileformat error, is was based upon loading the wrong library for the proper architecture in Linux. Ie trying to load a 64 bit on a 32 bit or OR ARM lib on an x86 processor.

**Comment by mysteryx93** [comment]
Sometimes it's working and sometimes not, for libassflac, libassalac and libasscd. I'm starting to think that they may have dependencies on other plugins and that it depends on the load order?

**Comment by mysteryx93** [comment]
Yep, somehow the load order is important. If I store the failed plugins in a list and then try them again after the others are loaded, then it works.
