### ISSUE TITLE
NuGet via linux will not compile, missing "DLL" bass.

### ISSUE THREAD

**Issue by LunaTheFoxgirl** [ManagedBass/ManagedBass#16]
ManagedBass on Linux throws an `DllNotFoundException` when trying to run bass. I heard that you just have to compile the source. But allowing linux builds too via NuGet would be really nice.
I'm on `Ubuntu 16.04` running the `low latency kernel`, `Mono JIT version 4.2.3`. Via `MonoDevelop 5.10`
Included bass files:
- libbass.so
- x64/libbass.so

Steps to replicate:
1. Download NuGet package.
2. Add `Bass.Init();`
3. Run code
![skaermbillede fra 2016-09-10 00-02-56](https://cloud.githubusercontent.com/assets/7032834/18404286/fb96db6c-76e9-11e6-974f-7766ce22433c.png)

So yeah, just a heads up! c:

**Comment by MathewSachin** [comment]
Is `libbass.so` being copied to the output folder?

Also, provide more details about the exception.

**Comment by Member1221** [comment]
It was fixed, by compiling the Linux version of the Interop library from source. The exception failed to find `bass.dll`. It was looking for the Windows version.
Is the NuGet package for Windows only?

**Comment by MathewSachin** [comment]
No, the package is not Windows only.

Please let me know the path to the referenced ManagedBass.dll in your .csproj file.

**Comment by Member1221** [comment]
```xml
    <Reference Include="ManagedBass">
      <HintPath>packages\ManagedBass.0.23.3\lib\net45\ManagedBass.dll</HintPath>
    <Reference Include="ManagedBass.PInvoke">
      <HintPath>RefDLL\ManagedBass.PInvoke.dll</HintPath>
```RefDLL is the folder where i put the linux version i compiled.

**Comment by MathewSachin** [comment]
Sorry for not being specific. I meant the Reference paths when you used the NuGet package not when you compiled yourself

**Comment by czesiu** [comment]
@Member1221 I'm using [this](https://github.com/czesiu/Luma.SmartHub.Audio.Bass/blob/master/install) script to install `bass` libraries in Linux system. They are copied to system folder and after that `DllNotFoundException` should disappear. I've tested it on Raspbian, but it should work also in Ubuntu.

**Comment by MathewSachin** [comment]
That seems strange @czesiu. Have you tried any other NuGet package with Linux support.

**Comment by czesiu** [comment]
I had same problem with running `ManagedBass` and I found this solution first. This is enough for me, so I didn't try with coping `*.so` files to some solution diirectories.

[Here](http://www.mono-project.com/docs/advanced/pinvoke/dllnotfoundexception/)`s more information about this problem.

**Comment by Member1221** [comment]
@czesiu I prefer to be able to have the unmanaged library beside the exe.

**Comment by MathewSachin** [comment]
@Member1221 Did you try placing `libbass.so` in `lib`folder under the output directory?

**Comment by MathewSachin** [comment]
@Member1221 Please try `Bass.Load()` method.

**Comment by lostromb** [comment]
To give some more context around this problem, when Mono tries to load a shared library in Linux, it invokes ld-linux.so (or else ld.so? They're similar...) to find the appropriate library, usually checking in /usr/lib and other common places in the system. Notably, this does not usually check the current process working directory first, as Windows does. This means if libbass.so is not installed on the system, Mono will throw an exception.

The workaround is to call Bass.Load("."); which explicitly invokes ld.so with a specific path so that it finds libbass.so in your working directory and loads it to memory.

**Comment by Jitnaught** [comment]
If you're getting the DllNotFoundException exception when using v2.0 of ManagedBass (no Load function) simply make sure that you have the correct libbass.so file in your output directory for the architecture your program is using. If you have the 32 bit version of libbass.so and your program is 64 bit this exception will occur, and vice versa.

**Comment by SlowLogicBoy** [comment]
I tried to resolve similar problem [here](https://github.com/ppy/osu-framework/issues/1540).

**Comment by Member1221** [comment]
Sorry, i've switched my codebase away from C#, so this is no longer an issue for me, if someone else experiences this issue they can keep this issue open, i guess.
