### ISSUE TITLE
Windows Store app is rejected

### ISSUE THREAD

**Issue by MagnusJohansson** [ManagedBass/ManagedBass#17]
Hi,

I tried to submit an application targeting Windows 10 UWP.
Note, this is **not** caught by the App Certification Kit, it is only detected in the submission review process.
All the ManagedBass API calls are reported having this error:
[ManagedBassError.txt](https://github.com/ManagedBass/ManagedBass/files/576248/ManagedBassError.txt)

> ...
> API BASS_MIDI_FontCompact in bassmidi.dll is not supported for this application type. ManagedBass.PInvoke.dll calls this API.
> ...

See attached text file with the full report.

**Comment by MathewSachin** [comment]
Thank you for testing that. One thing that I want to know is whether you uploaded a **Release** or **Debug** configuration and if you used **.Net Native**?

**Comment by MagnusJohansson** [comment]
Hi, thanks.

The issue has been resolved.

It turns out that all native DLLs that the .NET code references (or make DLL Imports to) has to be present in the package. The managed wrapper (ManagedBass.PInvoke.dll ) has references to bassmidi.dll, bassmix.dll and bass_fx.dll) and even though they are not used (by my app), they still have to be there.
It's odd that the local App Certification Kit doesn't catch that.

To your questions, yes Release build was used. I think .Net Native is done automatically when you build in release mode now.

Thanks, keep up the good work.
/M
