### ISSUE TITLE
Unable to detect loopback if base 64 bit dll is used

### ISSUE THREAD

**Issue by lahela223** [ManagedBass/ManagedBass#22]
Hi, I am creating some recording app which can record both the microphone and loopback devices

```csharp
for (int i = 0; Bass.RecordGetDeviceInfo(i, out deviceInfo); i++)
{
    Bass.RecordGetDeviceInfo(i, out deviceInfo)
    if (deviceInfo.IsLoopback)
    {
        //work to do
    }
    else
    {
        //work to do
    }
}
```
In 64bit version, it only returns microphone. But, in 32bit version of bass dll, it returned all devices.

Can you please suggest what is wrong?

**Comment by MathewSachin** [comment]
Call `Bass.Configure(Configuration.LoopbackRecording, true);` before initializing BASS or enumerating devices.

**Comment by lahela223** [comment]
abslutely fantastic thanks man it works

**Comment by lahela223** [comment]
hi its seems to be a problem with bass 64 bit i have tried with base.net library and same issue so i think its nothing to do with the managedbass library. i will try to post question on their forum and if i get any solution i will update here thanks
