### ISSUE TITLE
How can i playback audio from youtube videos/playlists

### ISSUE THREAD

**Issue by shomarisharpe** [ManagedBass/ManagedBass#23]
Hi how do i accomplish playback of youtube audio and youtube playlists?

**Comment by MathewSachin** [comment]
Sorry, I have no idea about that.
I think you may get the answer on stackoverflow.com

**Comment by MathewSachin** [comment]
Here's a related answer: http://stackoverflow.com/a/4014636

**Comment by czesiu** [comment]
You can use [YoutubeExtractor](https://github.com/flagbug/YoutubeExtractor) for this. I use it in my [project](https://github.com/czesiu/Luma.SmartHub.Plugins.Youtube). AFAIR there is no playlist provider so I added it [there](https://github.com/czesiu/Luma.SmartHub.Plugins.Youtube/blob/master/src/Luma.SmartHub.Plugins.Youtube/YoutubeExtractor/PlaylistUrlResolver.cs).
