### ISSUE TITLE
BassFx.Load() always returns false on UWP

### ISSUE THREAD

**Issue by theweavrs** [ManagedBass/ManagedBass#27]
My `bass_fx.dll` & `bass.dll` are in the same directory as all my other libs. Mainly:
```
\bin\x86\Debug
```
And I try loading the bassfx lib with this code:
```
 bool result = BassFx.Load();
```
And result is always false. It doesn't change even if I specifically put the folder path as the parameter. The result of this is that no effects, including the equalizer, work.

**Comment by MathewSachin** [comment]
Load has only been implemented for Win32, Linux and Mac.
Calling it is not necessary for working.

You can use BassFx in the same way you use Bass

**Comment by theweavrs** [comment]
oh, okay. So now the equalizer is working perfectly. I don't know why it wasn't working before though.

**Comment by theweavrs** [comment]
So one of the weirdest things I happened upon. If I don't do this:
```
var version = BassFx.Version;
```
before doing any of this:
```
int fxEQ = Bass.ChannelSetFX(handle, EffectType.PeakEQ, 0);
```
`fxEQ` remains 0. Now this is weird and unnecessary or perhaps it is required to load the lib? I don't know but it freaked me out.

**Comment by theweavrs** [comment]
So I looked into the source of `BassFx.cs` and got to know why this is happening. BassFx.Version calls this:
```
[DllImport(DllName)]
static extern int BASS_FX_GetVersion(); 
```
Which loads the dll into memory and makes it available for use. I could call any of the functions in `BassFx.cs` to do this but as this is least resource intensive, it is most suitable.

This, however, doesn't solve the main problem which is that this is unnecessary but that is a problem with BASS itself. What we can do to make this a little bit less inconspicuous and confusing is to mention the problem in the docs and also make another seperate method called `Load()` or some such which basically calls `BassFx.Version`. This would make everyone's lives easier.

Thanks.

**Comment by MathewSachin** [comment]
Your suggestion is good. I think that I have to do this for all the AddOns.

We can call Version property where available or use Bass.PluginLoad for plugins

**Comment by theweavrs** [comment]
Exactly...

**Comment by theweavrs** [comment]
@MathewSachin If you want I can make a pull request with the appropriate changes.

**Comment by MathewSachin** [comment]
Carry On 👍 👍

**Comment by MathewSachin** [comment]
Hi @theweavrs, Work begun in #29.

**Comment by MathewSachin** [comment]
Hi @theweavrs, Sorry for being late.

I feel like a change should be made to what we confirmed about Load method.

Rather than creating `Load` methods for every AddOn, it is better to remove it and state in README that AddOns need to be explicitly loaded.
