### ISSUE TITLE
Will ManagedBass be supported in .net Core 1.1 ?

### ISSUE THREAD

**Issue by sabiland** [ManagedBass/ManagedBass#28]
"Install-Package : Package ManagedBass 1.0.2 **is not compatible** with netcoreapp1.1 (.NETCoreApp,Version=v1.1). Package ManagedBass 1.0.2 supports:"

**Comment by Davidblkx** [comment]
It is right now, https://github.com/ManagedBass/ManagedBass/pull/25. But the nuget version isn't yet updated

**Comment by sabiland** [comment]
Uau cool, thx for quick reply.

**Comment by MathewSachin** [comment]
ManagedBass v2.0.0 released based on .NetStandard 1.4
