### ISSUE TITLE
ChannelGetLevelLeft / ChannelGetLevelRight LoWord incorrect

### ISSUE THREAD

**Issue by peppy** [ManagedBass/ManagedBass#32]
Expected values for these methods are 0 - 32768, but due to the way LoWord is implemented 32768 (max level) overflows to -32768.

Line at fault:
`public static short LoWord(this int DWord) => (short)DWord;`

**Comment by MathewSachin** [comment]
Please build and test with the latest commit added just now.

**Comment by peppy** [comment]
Tested and working as expected. Thanks for the quick fix!

As an aside, would be handy to know how far away the next nuget build is :)

**Comment by MathewSachin** [comment]
Released ManagedBass v2.0.1

**Comment by peppy** [comment]
thanks a lot 🥇
