### ISSUE TITLE
.net core 2.0 unable to load bass.dll

### ISSUE THREAD

**Issue by adragoset** [ManagedBass/ManagedBass#33]
.csproj
```<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="logging.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration.FileExtensions" Version="$(AspNetCoreVersion)" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="$(AspNetCoreVersion)" />
    <PackageReference Include="Microsoft.Extensions.FileProviders.Physical" Version="$(AspNetCoreVersion)" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="2.0.0-preview1-final"/>
    <PackageReference Include="CoreCompat.LibUsbDotNet" Version="2.2.8-r102"/>
    <PackageReference Include="ManagedBass" Version="2.0.1"/>
  </ItemGroup>
  <ItemGroup>
    <ContentWithTargetPath Include="drivers\bass.dll" TargetPath="\bass.dll" CopyToOutputDirectory="Always"/>
    <ContentWithTargetPath Include="drivers\libusb0.sys" TargetPath="\libusb0.sys" CopyToOutputDirectory="Always"/>
    <ContentWithTargetPath Include="drivers\libusb0.dll" TargetPath="\libusb0.dll" CopyToOutputDirectory="Always"/>
    <ContentWithTargetPath Include="drivers\zadig-2.3.exe" TargetPath="\zadig-2.3.exe" CopyToOutputDirectory="Always"/>
  </ItemGroup>
</Project>
```

bass.dll is being copied to the output directory correctly.

Fails at program start when trying to create the MediPlayer Class with error:

```
Unhandled Exception: System.TypeInitializationException: The type initializer for 'ManagedBass.MediaPlayer' threw an exceptio
n. ---> System.DllNotFoundException: Unable to load DLL 'bass': The specified module could not be found. (Exception from HRES
ULT: 0x8007007E)
   at ManagedBass.Bass.BASS_GetDevice()
   at ManagedBass.Bass.get_CurrentDevice()
   at ManagedBass.MediaPlayer..cctor()
   --- End of inner exception stack trace ---
   at ManagedBass.MediaPlayer..ctor()
   at part_tracker_service.Program..ctor() in C:\Users\adragose\Documents\Source\tooltracker\scanner_service\Program.cs:line
44
   at part_tracker_service.Program.Main(String[] args) in C:\Users\adragose\Documents\Source\tooltracker\scanner_service\Prog
ram.cs:line 53
```

**Comment by Davidblkx** [comment]
Are you starting the app from Visual Studio?
Have you try do add bass.DLL to the .csproj folder? If I'm remember it right when starting the app from vs the start folder is the one that have the .csproj

**Comment by adragoset** [comment]
You got it. When running debug mode in VS Code the dll's have to be in the root of the project folder sort of strange it's context isn't set to the debug folder. This solves the problem for now but will be difficult to make work when developing on this library cross platform because the correct .dll for the environment will need to be copied into the root while debugging. With the proj file i can specify which dll to target and copy to the output folder during the build.

**Comment by Davidblkx** [comment]
You can edit the launch.json and set context folder using the "cwd" property. Take a look at https://code.visualstudio.com/Docs/editor/debugging, is worth reading if you need a more customized debug environment

**Comment by alexdresko** [comment]
For anyone else who lands here, I was having a similar problem because I was using `libbass.so` from the root of `bass24-linux-arm.zip` on my Raspberry Pi 3. Turns out, I need to use the `libbass.so` from the `hardfp` directory in `bass24-linux-arm.zip`.

For the record, I'm running ManagedBass with ASP.NET Core 2.0.
