### ISSUE TITLE
ChannelGetLevelLeft/Right returns bad values when paused on macOS

### ISSUE THREAD

**Issue by swoolcock** [ManagedBass/ManagedBass#37]
If the playback state of the stream is `Paused`, calling `ChannelGetLevelLeft` and `ChannelGetLevelRight` will return `65535` and `-1` respectively.

Calling code:
https://github.com/ppy/osu-framework/blob/1b479fb947da193f099df062f696b3a6164da9e0/osu.Framework/Audio/Track/TrackBass.cs#L105

**Comment by MathewSachin** [comment]
I think it is wrong to call the GetLevel methods when the channel is Paused.
I think you should check for Paused state before you call those methods.

**Comment by swoolcock** [comment]
We are, but I was of the assumption that it would return the levels at the point it was paused.  If not, we can just keep a snapshot.  Regardless, I think the functionality should be consistent across platforms.

**Comment by MathewSachin** [comment]
If platform consistency is the issue, the problem must be with the BASS library itself.
Please try reporting on un4seen Forums: http://www.un4seen.com/forum/?board=1.0
