### ISSUE TITLE
attempting to jit compile method wrapper on iOS device

### ISSUE THREAD

**Issue by vandenbrakel** [ManagedBass/ManagedBass#38]
Hi, We are kinda lost here and hopefully you can shed some light on this issue.
We are getting the following error:
Our code:
// set the meta sync
Bass.ChannelSetSync(_stream, SyncFlags.End, 0, SampleFinished, IntPtr.Zero);
and the SampleFinished method:
private void SampleFinished(int Handle, int Channel, int Data, IntPtr User)
{
OnComplete?.Invoke();
if (loopState == false) SamplesPlayingCount--;
}
attempting to jit compile method wrapper
Any thoughts?
TX!

**Comment by MathewSachin** [comment]
Please see [Getting Started - iOS guide](https://github.com/ManagedBass/Home/blob/master/docs/Getting%20Started/iOS.md).

Apply MonoPInvokeCallback and make the callback method static.

**Comment by vandenbrakel** [comment]
Hi,

Thank you some much. I missed that guide (and especially the last steps).
Maybe it should be listed in the Readme somewhere. Or did I mis that also?

Great,

Thanks. We are finishing up our first bass / managedbass app. I'll let you
know and make I nice donation if we got it all working.

Managed bass is real good so far.

Thanks again.

Sander

**Comment by MathewSachin** [comment]
You are welcome
