### ISSUE TITLE
System.TypeLoadException in VS2015

### ISSUE THREAD

**Issue by Xan-Kun** [ManagedBass/ManagedBass#42]
I installed ManagedBase 2.0.3 via Package Manager and added the base.dll to the output directory.

Now I get 

`System.TypeLoadException: 'Could not load type 'ManagedBass.Bass' from assembly 'ManagedBass, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.'`

when calling  `Bass.Init();`

I tried different target platforms and versions, but to no avail.

**Comment by MathewSachin** [comment]
Please try compiling your app to .Net 4.6.1

**Comment by Xan-Kun** [comment]
Thanks for the answer. It works now.  I had to create a new solution from scratch and add a new .NET 4.6.1 project. Then I installed ManagedBass package via NuGet, downloaded the bass24.zip and copied the bass.dll in the root folder of the zip to the bin/Debug folder.

Now it is initializing without error.
