### ISSUE TITLE
Error building for device builds

### ISSUE THREAD

**Issue by Clancey** [ManagedBass/ManagedBass#43]
MTOUCH: Error MT2101: Can't resolve the reference 'System.IntPtr ManagedBass.DynamicLibrary::Load(System.String,System.String)', referenced from the method 'System.Boolean ManagedBass.Fx.BassFx::Load(System.String)' in 'ManagedBass, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. (MT2101)

Yes I followed the instructions from the sample. I did modify it for BaseFX as well.

```-gcc_flags "-L${ProjectDir} -lbass -lbass_fx -framework CFNetwork -framework AudioToolbox -framework SystemConfiguration -framework Accelerate -force_load ${ProjectDir}/libbass.a -force_load ${ProjectDir}/libbass_fx.a"```

**Comment by Clancey** [comment]
This is caused by Nuget mismatch.  ManagedBass was updated to 2.0.3, but ManagedBass.Fx is still on an old version 2.0 which relies on ManagedBass 2.0.

**Comment by Clancey** [comment]
Now that 2.0.4 is out, and it is required to run on iOS. Any chance you can update the ManagedBass.Fx nuget?

**Comment by MathewSachin** [comment]
There have not been any changes in ManagedBass.Fx code.

Did updating ManagedBass package after installing MamagedBass.Fx work?

**Comment by Clancey** [comment]
Nope, There have not been any changes to ManagedBass.Fx. But there have been signature changes in ManagedBass. Since it was compiled against an older version, Xamarin cannot AOT due to the signature change.

**Comment by MathewSachin** [comment]
Oops. Found it. The `DynamicLibrary.Load` method is the culprit.

So, this needs to be fixed for all packages.

BTW, I was intending to release the packages using `DllMap`. See #30.
Could you please help me with me that.
Since, otherwise I have to release all the packages after DllMap is done.

**Comment by Clancey** [comment]
Do you need help implementing it or testing it?

**Comment by MathewSachin** [comment]
I need help in Testing. I don't have an iOS or Mac device.

**Comment by Clancey** [comment]
Sure. I can test. Do you have a sample I can run?

**Comment by MathewSachin** [comment]
I don't have a complete sample.

But, I've attached `ManagedBass.dll` and modified `ManagedBass.Fx.dll`.
Also, there is an `app.config` file. Include it in your iOS project.
If you already have `app.config` file in your project, add the `dllmap` line to it.

Thank You

[ManagedBass.Fx.zip](https://github.com/ManagedBass/ManagedBass/files/1440897/ManagedBass.Fx.zip)

**Comment by Clancey** [comment]
I have tried many different things.  Leaving it as app.config.Checked the output, it is properly renamed to *.exe.config.  Tried ManagedBass.Fx.dll.config  No matter what same error.

```
 System.DllNotFoundException: bass_fx
  at (wrapper managed-to-native) ManagedBass.Fx.BassFx:BASS_FX_GetVersion ()
  at ManagedBass.Fx.BassFx.get_Version () [0x00000] in <aa5af0715af74d2d874abf955dab0b8a>:0 
```

**Comment by MathewSachin** [comment]
I'm not sure about this.

Did you add extra mtouch arguments for BassFx?

**Comment by Clancey** [comment]
Yes, if I didn't I couldn't build. The pinvoke is what is failing not linking.
```
-gcc_flags "-L${ProjectDir} -lbass -lbass_fx -framework CFNetwork -framework AudioToolbox -framework SystemConfiguration -framework Accelerate -force_load ${ProjectDir}/libbass.a -force_load ${ProjectDir}/libbass_fx.a"
```

**Comment by Clancey** [comment]
Looks like there might be a bug in the Xamarin side. https://bugzilla.xamarin.com/show_bug.cgi?id=60520

Anyway to push the nuget without the dllmap for now?

**Comment by MathewSachin** [comment]
Ok. I'll release nuget ASAP.

**Comment by Clancey** [comment]
Fixed thanks

**Comment by MathewSachin** [comment]
@Clancey Please see the latest replies on the thread you reported to Xamarin about dllmap on iOS.
https://bugzilla.xamarin.com/show_bug.cgi?id=60520

Please check of the issue is resolved.

>Rolf Bjarne Kvinge [MSFT]
Renaming the app.config to ManagedBass.Fx.dll.config and setting the build action to BundleResource worked for me.
Can you try that too?
https://gist.github.com/rolfbjarne/2f92ab8757dc1d2fa51ab34e63247418
