### ISSUE TITLE
ManageBass crashing on dotnet builds on linux

### ISSUE THREAD

**Issue by RCSDustinBond** [ManagedBass/ManagedBass#48]
@MathewSachin 

I would like to contact you regarding some crashes we are seeing when using ManagedBass on a Linux dotnet core build. I am current in contact with Ian trying to track the issue. As I'm not as familiar with the code base and linux operating system, I'll attach his question to us: 

> It looks like the BASSmix library was unable to find the BASS_GetVersion function (which it calls internally). But it also looks like the BASS library is loaded, so I'm not sure why that happened. My guess would be that the BASS library wasn't loaded with global scope (RTLD_GLOBAL).

> Is there any option regarding the scope of loaded libraries?

**Comment by RCSDustinBond** [comment]
Below is the sample code I am using  (Make sure you use the latest assemblies)
I crash when trying to run the dotnet core  assembly on linux

> using System;
using ManagedBass;
using ManagedBass.Mix;
using ManagedBass.Enc;
using ManagedBass.Fx;
namespace rcs.raptor.bass
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("MANAGEDBASS");
            Console.WriteLine("BASS Version: {0:X}",  Bass.Version);
            Console.WriteLine("BASSEnc Version: {0:X}", BassEnc.Version);  //crashes here
            Console.WriteLine("BASSMix Version: {0:X}", BassMix.Version); //crashes here
            Console.WriteLine("BASSFx Version: {0:X}", BassFx.Version); //crashes here
        }
    }
}

**Comment by MathewSachin** [comment]
I'm sorry I'm not familiar with this issue. I'm unable to directly help here because I have not tried running ManagedBass on .Net core on Linux.

**Comment by RCSDustinBond** [comment]
When you change the project to be .Net Standard 1.4 compliant, did anyone run any test on linux? 
Maybe you can help me? I'm trying to understand where we load the libbass.so, libbassmix.so, libbassenc.so and libbassfx.so libraries. 

const string DllName = "bass";
I'm assuming this is being done in the "[DllImport(DllName)]"  call?

How is "bass" translated to "libbass.so"? I'm sure i'm missing a simple concept. Just trying to trouble shoot the crash.

**Comment by MathewSachin** [comment]
You are right `bass` automatically changes to `libbass.so` when loading using `DllImport` on Linux.
A library is loaded on runtime when a function with `DllImport` applied is called.

**Comment by RCSDustinBond** [comment]
It appears the problem is related to dependency dlls not being loaded or accessible on linux. The sample code below will solve the problem.
````
class Program
    {
        [DllImport("libdl.so")]
        static extern IntPtr dlopen(string filename, int flags);

        static void Main(string[] args)
        {
            if (RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
            {
                Console.WriteLine("Windows Load Library");
            }
            else if (RuntimeInformation.IsOSPlatform(OSPlatform.Linux))
            {
                Console.WriteLine("Linux Load Library");
                Console.WriteLine("BASSLib: {0:X}", dlopen("libbass.so", 0x101)); // 0x101 = RTLD_GLOBAL+RTLD_LAZY
                //Console.WriteLine("BASSLibMix: {0:X}", dlopen("libbassmix.so", 0x101));
                //Console.WriteLine("BASSLibEnc: {0:X}", dlopen("libbassenc.so", 0x101));
                //Console.WriteLine("BASSLibFx: {0:X}", dlopen("libbass_fx.so", 0x101));
            }
            else if (RuntimeInformation.IsOSPlatform(OSPlatform.OSX))
            {
                Console.WriteLine("OSX Load Library");
            }
            else
                throw new NotSupportedException();

            Console.WriteLine("MANAGEDBASS Library Version Checks");
            Console.WriteLine("BASS Version: {0:X}", ManagedBass.Bass.Version);
            Console.WriteLine("BASSEnc Version: {0:X}", ManagedBass.Enc.BassEnc.Version);
            Console.WriteLine("BASSFx Version: {0:X}", ManagedBass.Fx.BassFx.Version);
            Console.WriteLine("BASSMix Version: {0:X}", ManagedBass.Mix.BassMix.Version);
        }
    }
````

**Comment by alexdresko** [comment]
For anyone else who lands here, I was having a similar problem because I was using `libbass.so` from the root of `bass24-linux-arm.zip` on my Raspberry Pi 3. Turns out, I need to use the `libbass.so` from the `hardfp` directory in `bass24-linux-arm.zip`.

For the record, I'm running ManagedBass with ASP.NET Core 2.0.
