### ISSUE TITLE
How to change the position of Bass.dll

### ISSUE THREAD

**Issue by shyakocat** [ManagedBass/ManagedBass#49]
Can i move the "bass.dll" to another path?
if can,how to do that.

**Comment by MathewSachin** [comment]
If you are on Windows, You can DllImport LoadLibrary function from Kernel32.dll and call it with the path to bass.dll before using any functions from ManagedBass.

The code for DllImpprt can be found by a Google search.

**Comment by shyakocat** [comment]
Thank you- @MathewSachin
