### ISSUE TITLE
Missing type `ManagedBass.Plugin` referenced in `ManagedBass.Midi`

### ISSUE THREAD

**Issue by MillKaDe** [ManagedBass/ManagedBass#53]
Using Nuget, I installed `ManagedBass` (v2.0.4) and `ManagedBass.Midi` (v2.0.0).

`ManagedBass.Midi` (v2.0.0) references type `ManagedBass.Plugin`, which is not available anymore in v2.0.4 of `ManagedBass`.
To solve the issue, I installed v2.0.0 of `ManagedBass`, instead of v2.0.4.

Any plans to update `ManagedBass.Midi` and the other addons to be compatible with the latest `ManagedBass` (v2.0.4) ?

**Comment by MathewSachin** [comment]
I did not update the packages due to #45, which would require all packages to be released again.
As soon as someone helps with testing #45, I will release the new packages.
