### ISSUE TITLE
Sound would be the mumble if I change the Frequency to 16000 for Recording.

### ISSUE THREAD

**Issue by wyy272176594** [ManagedBass/ManagedBass#55]
Hi,
I use Bass.RecordStart() for Recording ,but I find if I change the Frequency to 16000, the sound would be 
the mumble. So how to set the Frequency to 16000 rate with 16 bits in the right way?

**Comment by MathewSachin** [comment]
A frequency of 44100Hz is required for good recording. Anything below that frequency will have poor quality

**Comment by wyy272176594** [comment]
Thanks. But ASR api needs wav with 16000, and I find Recording 16000 with NAudio is also clear. So does it have any way to improve 16000's quality with Bass.Thank you.

**Comment by MathewSachin** [comment]
I think your issue might not be related to ManagedBass but the BASS library.

Try asking ob BASS forums: http://www.un4seen.com/forum/?board=1.0

**Comment by wyy272176594** [comment]
OK, Thank you.
