### ISSUE TITLE
PluginGetInfo Crashing on Linux

### ISSUE THREAD

**Issue by RCSDustinBond** [ManagedBass/ManagedBass#59]
Mathew,

I found a crash in the Linux versions of PluginGetInfo and probably other places using Marshal.PtrToStringAnsi

The following example will **crash** if exts == IntPtr.Zero
**public string FileExtensions => Marshal.PtrToStringAnsi(exts);**

I'm contacting you for i'm not sure the best fit
1) Use Extensions.Ptr.ToStringUtf8, this has protection against ( IntPtr.Zero)
**public string FileExtensions => Extensions.PtrToStringUtf8(exts);**

2) Use a simple IntPtr.Zero check?
**string FileExtensions => (exts != IntPtr.Zero) ? Marshal.PtrToStringAnsi(exts) : string.Empty;**

Please advice of your recommended fix, and I will apply them to the code..

**Comment by MathewSachin** [comment]
I think the 2nd option would be better
