### ISSUE TITLE
Can't get ManagedBass.Wasapi to install

### ISSUE THREAD

**Issue by seckela** [ManagedBass/ManagedBass#62]
I keep getting the error:

> Install-Package : Could not install package 'ManagedBass.Wasapi 2.0.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by MathewSachin** [comment]
ManagedBass is built on .NET Standard 1.4.
So, atleast .NET Framework v4.6.1 is required.

**Comment by seckela** [comment]
Thank you, Upgrading the .net version fixed this.
