### ISSUE TITLE
Raspberry Pi - No Sound on Playback

### ISSUE THREAD

**Issue by drwharris** [ManagedBass/ManagedBass#65]
I am using Raspian Buster and Dotnet Core 2.2 (C#) to play a single MP3 file. I have a method as follows:

    public static void Siren()
    {
            // Init BASS using the default output device
            if (Bass.Init())
            {
                // Create a stream from a file
                var stream = Bass.CreateStream("/home/pi/clock/example.mp3");

                if (stream != 0)
                {
                    Console.WriteLine("Playing Siren");
                    var success = Bass.ChannelPlay(stream, true); // Play the stream
                    if (success)
                    {
                        Console.WriteLine("Playback complete");
                    }
                    else
                    {
                        Console.WriteLine("Playback Failed: " +  Bass.LastError);
                    }

                }
                else
                {
                    Console.WriteLine("Error: {0}!", Bass.LastError);
                }

                // Free the stream
                Bass.StreamFree(stream);

                // Free current device.
                Bass.Free();
            }
            else
            {
                Console.WriteLine("BASS could not be initialized!");
            }
    }

On the console I get "Playing Siren" and "Playback complete" but no audio is heard. If I run from a command line "omxplayer /home/pi/clock/example.mp3" I get the appropriate audio (through HDMI output).

Any help appreciated.

Andrew

**Comment by drwharris** [comment]
Ive since found that if I run omxplayer via C# Process.Start I have to specifically tell it to use the HDMI output channel. Wondering if I have to do the same with ManageBass but dont know how.

**Comment by drwharris** [comment]
@MathewSachin ?

**Comment by MathewSachin** [comment]
Sorry I'm not experienced with Raspberry Pi.
But, this seems to me like more related to BASS itself rather than ManagedBass.
Someone on the BASS forums might be able to help you better.

**Comment by drwharris** [comment]
@MathewSachin Its kind of irrelevant if its raspberry (Debian Linux) or Windows. I am asking how to set the output device using your wrapper.

From what I can tell, I need to use Bass.CurrentDevice property which wraps the underlying BASS_SetDevice (http://www.un4seen.com/doc/#bass/BASS_SetDevice.html).

So I have this code:

        for (var i = 0; Bass.GetDeviceInfo(i, out var devInfo); ++i)
        {
                Console.WriteLine(i + ": " + devInfo.Name);
        }
        Console.WriteLine("Current Device: " + Bass.CurrentDevice);

Which outputs:

0: No sound
1: Default
2: bcm2835 ALSA: bcm2835 ALSA
3: bcm2835 ALSA: bcm2835 IEC958/HDMI

Current Device: -1

So I call Bass.Init(3) and Console.WriteLine("Current Device: " + Bass.CurrentDevice); which reports "Current Device: 3" but still no sound.

Full Code:

    public static void Siren()
    {
        for (var i = 0; Bass.GetDeviceInfo(i, out var devInfo); ++i)
        {
                Console.WriteLine(i + ": " + devInfo.Name);
        }
        Console.WriteLine(Bass.CurrentDevice);

        if (Bass.Init(3))
        {
            Console.WriteLine(Bass.CurrentDevice);
            var stream = Bass.CreateStream("/home/pi/clock/example.mp3");

            if (stream != 0)
            {
                Console.WriteLine("Playing Siren");
                var success = Bass.ChannelPlay(stream, true); 
                if (success)
                {
                    Console.WriteLine("Playback complete");
                }
                else
                {
                    Console.WriteLine("Playback Failed: " + Bass.LastError);
                }

            }
            else
            {
                Console.WriteLine("Error: {0}!", Bass.LastError);
            }

            Bass.StreamFree(stream);

            Bass.Free();
        }
        else
        {
            Console.WriteLine("BASS could not be initialized!");
        }
    }

**Comment by MathewSachin** [comment]
The way you are setting the device is correct.
Also, check if the device is muted or if the volume is low.
If it still doesn't work, It does not seem to me as an issue that could be resolved in the wrapper. It might be a problem with the underlying BASS library. For confirming, please try using the Bass.NET library and let me know if it works.

**Comment by guenterrudigier** [comment]
Bass_ChannelPlay starts the playback and does not wait until finished. So it is not a good idea to call StreamFree(stream) and Bass.Free() right after ChannelPlay.

Remove StreamFree and Free and thy again. If it works you need to wait until the file is played to end and Free afterwards. You can use a end sync for that...

**Comment by drwharris** [comment]
@guenterrudigier  Thank you and good call. Rookie mistake! So I now have

    public static void Siren()
    {
        Console.WriteLine(Bass.CurrentDevice);
        if (Bass.Init(3))
        {
            Console.WriteLine(Bass.CurrentDevice);
            var stream = Bass.CreateStream("/home/pi/clock/example.mp3");

            if (stream != 0)
            {
                Console.WriteLine("Playing Siren");
                var success = Bass.ChannelPlay(stream, true);
                if (success)
                {
                    Console.WriteLine("Playback complete");
                }
                else
                {
                    Console.WriteLine("Playback Failed: " + Bass.LastError);
                }
            }
            else
            {
                Console.WriteLine("Error: {0}!", Bass.LastError);
            }
        }
        else
        {
            Console.WriteLine("BASS could not be initialized!");
        }
    }

But the same result unfortunately.

**Comment by drwharris** [comment]
Interestingly I added timestamp output and the result is:

2019-10-18 09:00:35.477: -1
2019-10-18 09:00:35.624: 3
2019-10-18 09:00:35.628: Playing Siren
2019-10-18 09:00:35.630: Playback complete

Note the 12 millisecond between playing and completing. Not sure if thats expected.

**Comment by guenterrudigier** [comment]
Again: Bass.ChannelPlay starts the playback and has nothing to do with completed! So the 2ms (not 12 :-)) are fine in my opinion...

Can you set a breakpoint after Bass.ChannelPlay and check if you hear any sound. Possibly you close the whole app after calling Siren()?! 

I would also add Bass.ChannelIsActive(stream) after Bass.ChannelPlay() to check if the playback is running. Also check the return value from Bass.ChannelGetAttribute(stream, ChannelAttribute.Volume)

You should also check the volume of your output device, possibly muted by linux system?!

**Comment by RCSDustinBond** [comment]
Are there any open issues related to Bass Running on Raspberry PI?  I've been using this with out any issue for about 1 year now? I think we can close this ticket..

**Comment by drwharris** [comment]
Sorry, I've been on other things and no spare time to work on this. Im happy to close if others are working.
