### ISSUE TITLE
Where is struct BASS_FX_VOLUME_PARAM mapping for?

### ISSUE THREAD

**Issue by MikiraSora** [ManagedBass/ManagedBass#69]
I want to apply volume adjust for mixer channel.
but I found that there is no any C# struct for BASS_FX_VOLUME_PARAM.
![image](https://user-images.githubusercontent.com/7549173/76048356-850f4d00-5fa0-11ea-879d-60a828d40fa3.png)
So how to use Bass.ChannelSetFX,even I got a Type error?

**Comment by MikiraSora** [comment]
I have to reference ManagedBass.Fx and get `BassFx.Version` , 'Bass.ChannelSetFX' could work.

**Comment by olitee** [comment]
In your case, since you only need to change the volume level, have you considered using the volume attribute, instead of an effect?

`Bass.ChannelSetAttribute(mixer, ChannelAttribute.Volume, 0);`

The volume attribute simply uses a double value 0.0 to 1.0 to represent gain. Rather than a struct.

**Comment by MikiraSora** [comment]
Yep but I want to implement fade in/out for mix channel , so ChannelSetAttribute isnt solution.
In my post https://www.un4seen.com/forum/?topic=18832.0 and they told me I should use FX to deal with

**Comment by olitee** [comment]
I have done just that using the `ChannelSlideAttribute()` method:

https://github.com/ManagedBass/ManagedBass/blob/996a97706d63ac00a52e6e1be618c7c19cc985bd/src/Bass/Shared/Bass/PInvoke/Channels.cs#L641

I set the inital value using the `ChannelSetAttribute`, then execute the fade in by calling `ChannelSlideAttribute`.

It's just a different way of achieving the same thing. Your alternative would be manually implement the missing struct.

**Comment by MikiraSora** [comment]
Does `ChannelSlideAttribute()`or`ChannelSetAttribute` work with mix channel when this channel is decoding and not play.
I try call both methods but no changed.

**Comment by olitee** [comment]
That's odd ... is that what you've found?

It's just that I use those methods exclusively with **decoding** channels, and they work just fine. But maybe my situation is slightly different.

My playback is done by streaming the decoding channels, and writing to the audio output - so it's effectively the same as writing to a file.

I have a fairly long chain of decoding channels into mixers, splitters and so on - so maybe that's the difference.

You may find that passing your mixer through a splitter, then passing THAT to your encoder might work.

Failing that, it's looking like you might have to implement that missing struct.

**Comment by MikiraSora** [comment]
oh maybe I solved.
I check bass.h and found that `BASS_FX_VOLUME` is 9 , but EffectType.Volume is `65539`.
![](https://puu.sh/FhWmd/de365b820b.png)
![](https://puu.sh/FhWmu/6b8d40d1c7.png)
When I force pass 9 to SetChannelFX() , it works! but I pass '65539' to method , it not.
I dont know why EffectType.Volume is different with BASS_FX_VOLUME.

**Comment by olitee** [comment]
I know this is closed, but just to clarify - after some digging:

From bass.h
`BASS_FX_VOLUME = 9 `

and from bass_fx.h
`BASS_FX_BFX_VOLUME = 65539`

The 2nd Volume effect type is actually part of the BassFX add-on. It appears that ManagedBass has simplified the implementation by only referencing the BassFX Volume effect type.

It is odd that both bass.h and bass_fx.h define their own version of the volume effect type.

**Comment by MikiraSora** [comment]
@olitee So I think c# EffectType should add "VolumeFX" field for the later.

**Comment by olitee** [comment]
Yeah, it's awkward, as the naming convention is already set - but changing it would be a breaking change for anyone using the current implementation.

@MathewSachin any guidance? The fs types prefixed with `BASS_FX_BFX_` are all dependent on the BassFX add on - but changing all of them (e.g. `Rotate` to `BFXRotate`) would be disruptive.

We can either add the Bass (non-FX) option as something like `BassVolume` ... with some further explanation in the metadata?

Or we could obsolete the current `Volume` value for a few releases, with a view to transitioning it to the correct value? Slow, but would be clearer in the long run?
