### ISSUE TITLE
Bass.Init() crashes under Ubuntu

### ISSUE THREAD

**Issue by morphx666** [ManagedBass/ManagedBass#70]
The application works just fine under Windows, but under linux (Ubuntu 19.10 , as well as Raspian Buster) crashes with the following output:

> Stacktrace:
> 
>   at <unknown> <0xffffffff>
>   at (wrapper managed-to-native) ManagedBass.Bass.Init (int,int,ManagedBass.DeviceInitFlags,intptr,intptr) [0x00002] in <13ebafe14ff74b79b573a88d4b10a623>:0
>   at SharpFlappyBird.FlappyBird.SetupBASS () [0x000a5] in <9d38edb169fd4c2f953e2dfcaa75f995>:0
>   at SharpFlappyBird.FlappyBird..ctor (System.Windows.Forms.Control,System.Drawing.Image,System.Drawing.Image,System.Drawing.Image,System.Drawing.Image,System.Drawing.FontFamily,string,string,string) [0x0018b] in <9d38edb169fd4c2f953e2dfcaa75f995>:0
>   at SharpFlappyBird.FormMain..ctor () [0x000cd] in <9d38edb169fd4c2f953e2dfcaa75f995>:0
>   at (wrapper remoting-invoke-with-check) SharpFlappyBird.FormMain..ctor () [0x00018] in <9d38edb169fd4c2f953e2dfcaa75f995>:0
>   at SharpFlappyBird.Program.Main () [0x0000b] in <9d38edb169fd4c2f953e2dfcaa75f995>:0
>   at (wrapper runtime-invoke) object.runtime_invoke_void (object,intptr,intptr,intptr) [0x0004c] in <d0e12f672b88444ab4b6d9b2ecf20142>:0
> /proc/self/maps:
> 4128c000-4131c000 rwxp 00000000 00:00 0 
> 415eb000-415fb000 rwxp 00000000 00:00 0 
> 558b55281000-558b552ac000 r--p 00000000 08:05 4461277                    /usr/bin/mono-sgen
> 558b552ac000-558b555a9000 r-xp 0002b000 08:05 4461277                    /usr/bin/mono-sgen
> 558b555a9000-558b556d6000 r--p 00328000 08:05 4461277                    /usr/bin/mono-sgen
> 558b556d7000-558b556de000 r--p 00455000 08:05 4461277                    /usr/bin/mono-sgen
> 558b556de000-558b556e3000 rw-p 0045c000 08:05 4461277                    /usr/bin/mono-sgen
> 558b556e3000-558b55774000 rw-p 00000000 00:00 0 
> 558b57743000-558b57e5d000 rw-p 00000000 00:00 0                          [heap]
> 7f6298000000-7f6298021000 rw-p 00000000 00:00 0 
> 7f6298021000-7f629c000000 ---p 00000000 00:00 0 
> 7f629c000000-7f629c021000 rw-p 00000000 00:00 0 
> 7f629c021000-7f62a0000000 ---p 00000000 00:00 0 
> 7f62a0000000-7f62a0026000 rw-p 00000000 00:00 0 
> 7f62a0026000-7f62a4000000 ---p 00000000 00:00 0 
> 7f62a4000000-7f62a4035000 rw-p 00000000 00:00 0 
> 7f62a4035000-7f62a8000000 ---p 00000000 00:00 0 
> 7f62a8000000-7f62a8021000 rw-p 00000000 00:00 0 
> 7f62a8021000-7f62ac000000 ---p 00000000 00:00 0 
> 7f62aca0c000-7f62aca0d000 ---p 00000000 00:00 0 
> 7f62aca0d000-7f62aca0e000 rw-p 00000000 00:00 0 
> 7f62aca0e000-7f62aca16000 ---p 00000000 00:00 0 
> 7f62aca16000-7f62acc0d000 rw-p 00000000 00:00 0 
> 7f62acc0d000-7f62acc0e000 ---p 00000000 00:00 0 
> 7f62acc0e000-7f62acc0f000 rw-p 00000000 00:00 0 
> Memory around native instruction pointer (0x4b96):
> Segmentation fault (core dumped)

I hope I'm missing something obvious...

**Comment by MathewSachin** [comment]
Well, on linux a different set of BASS libraries are used instead of `dll` files like `libbass.so`.

**Comment by morphx666** [comment]
I have used BASS before (with BASS.NET) and I'm aware of different set of libraries required under different platforms.

I can assure you that the program is providing the correct [library based on the platform](https://github.com/morphx666/SharpFlappyBird/blob/54871e4c7870033d9f749afeaa1f1a47d4f3cc2c/SharpFlappyBird/FlappyBird.cs#L365).

**Comment by MathewSachin** [comment]
I think Ubuntu might not be able to able to find a library if it is not in search path.

Try updating `LD_LIBRARY_PATH` environment variable in your app before calling `Bass.Init` to the folder where the library to be loaded is present.

**Comment by morphx666** [comment]
I'll give it a try but, as I mentioned before, I have another project using BASS.NET which works just fine, using almost the exact same code to provide the appropriate library.

**Comment by MathewSachin** [comment]
I mentioned that workaround because linux does not search for libraries to load in the app's working directory like what Windows does. I don't know if Bass.Net internally updates that environment variable.

**Comment by morphx666** [comment]
It didn't work.
After setting the `LD_LIBRARY_PATH` to the path where the program and its libraries reside I still get the exact same error.

This is the code I used to setup the variable:

> export LD_LIBRARY_PATH=/mnt/6EA034F0A034C07F/Users/xavie/Dropbox/Projects/SharpFlappyBird/Release/

**Comment by MathewSachin** [comment]
Another thing to try is to load manually, try something like what is done in this class:

```csharp
using System;
using System.Runtime.InteropServices;
using System.IO;

namespace ManagedBass
{
    /// <summary>
    /// Supports loading libraries dynamically on Desktop.
    /// </summary>
    public static class DynamicLibrary
    {
        const string LinuxDllName = "libdl.so",
            MacDllName = "/usr/lib/libSystem.dylib",
            WinDllName = "kernel32.dll";

        const int RtldNow = 2;

        [DllImport(LinuxDllName, EntryPoint = "dlopen")]
        static extern IntPtr LoadLinux(string FileName, int Flags = RtldNow);

        [DllImport(LinuxDllName, EntryPoint = "dlclose")]
        static extern bool UnloadLinux(IntPtr hLib);

        [DllImport(MacDllName, EntryPoint = "dlopen")]
        static extern IntPtr LoadMac(string FileName, int Flags = RtldNow);
        
        [DllImport(MacDllName, EntryPoint = "dlclose")]
        static extern bool UnloadMac(IntPtr hLib);
        
        [DllImport(WinDllName, EntryPoint = "LoadLibrary")]
        static extern IntPtr LoadWin(string DllToLoad);

        [DllImport(WinDllName, EntryPoint = "FreeLibrary")]
        static extern bool UnloadWin(IntPtr hLib);

        static string GetPath(string FileName, string Folder)
        {
            return !string.IsNullOrWhiteSpace(Folder) ? Path.Combine(Folder, FileName) : FileName;
        }

        /// <summary>
        /// Loads a Library.
        /// </summary>
        /// <returns>The Handle of the loaded library on success, else <see cref="IntPtr.Zero"/>.</returns>
        public static IntPtr Load(string DllName, string Folder)
        {
            try { return LoadWin(GetPath($"{DllName}.dll", Folder)); }
            catch
            {
                try { return LoadLinux(GetPath($"lib{DllName}.so", Folder)); }
                catch
                {
                    try { return LoadMac(GetPath($"lib{DllName}.dylib", Folder)); }
                    catch { return IntPtr.Zero; }
                }
            }
        }

        /// <summary>
        /// Unloads a library loaded using <see cref="Load"/>.
        /// </summary>
        /// <param name="hLib">The Handle of a library loaded using <see cref="Load"/>.</param>
        /// <returns>true on success, else false.</returns>
        public static bool Unload(IntPtr hLib)
        {
            try { return UnloadWin(hLib); }
            catch
            {
                try { return UnloadLinux(hLib); }
                catch
                {
                    try { return UnloadMac(hLib); }
                    catch { return false; }
                }
            }
        }
    }
}
```

**Comment by morphx666** [comment]
Sorry for the delay.
I tried your suggestion and I keep getting the exact same error message.

I'm afraid the problem is not related with ManagedBass not being able to load the library, because if I intentionally leave the bass libraries out, the error is the expected "DllNotFoundException" :

    Unhandled Exception:
    System.DllNotFoundException: bass
      at (wrapper managed-to-native) ManagedBass.Bass.Init(int,int,ManagedBass.DeviceInitFlags,intptr,intptr)

**Comment by morphx666** [comment]
After running numerous tests, I'm afraid there's some issue with `mono`.

The program runs just fine under Windows, but if I run the program using mono (with `-v` argument) it produces a similar error message to what I get under other platforms.

So far I have tested under Linux/Ubuntu, macOS/Catalina and RaspberryPi/Raspbian.

In case it helps, here's the output of running the program under Windows using mono:

```
converting method void System.OutOfMemoryException:.ctor (string)
Method void System.OutOfMemoryException:.ctor (string) emitted at 00000207FA810B60 to 00000207FA810BAD (code length 77) [SharpFlappyBird.exe]
converting method (wrapper runtime-invoke) object <Module>:runtime_invoke_void__this___object (object,intptr,intptr,intptr)
Method (wrapper runtime-invoke) object <Module>:runtime_invoke_void__this___object (object,intptr,intptr,intptr) emitted at 00000207FA810BF0 to 00000207FA810D40 (code length 336) [SharpFlappyBird.exe]
converting method void System.SystemException:.ctor (string)
Method void System.SystemException:.ctor (string) emitted at 00000207FA810D50 to 00000207FA810D9D (code length 77) [SharpFlappyBird.exe]
converting method void System.Exception:.ctor (string)
Method void System.Exception:.ctor (string) emitted at 00000207FA810DC0 to 00000207FA810E18 (code length 88) [SharpFlappyBird.exe]
converting method void System.Exception:.cctor ()
Method void System.Exception:.cctor () emitted at 00000207FA810E40 to 00000207FA810E81 (code length 65) [SharpFlappyBird.exe]
converting method (wrapper runtime-invoke) object object:runtime_invoke_void (object,intptr,intptr,intptr)
Method (wrapper runtime-invoke) object object:runtime_invoke_void (object,intptr,intptr,intptr) emitted at 00000207FA810EA0 to 00000207FA810FD0 (code length 304) [SharpFlappyBird.exe]
converting method (wrapper alloc) object object:AllocSmall (intptr,intptr)
Method (wrapper alloc) object object:AllocSmall (intptr,intptr) emitted at 00000207FA810FF0 to 00000207FA8110FB (code length 267) [SharpFlappyBird.exe]
converting method void System.Exception:Init ()
Method void System.Exception:Init () emitted at 00000207FA811110 to 00000207FA811198 (code length 136) [SharpFlappyBird.exe]
converting method void System.Exception:set_HResult (int)
Method void System.Exception:set_HResult (int) emitted at 00000207FA8111B0 to 00000207FA8111D1 (code length 33) [SharpFlappyBird.exe]
converting method void System.NullReferenceException:.ctor (string)
Method void System.NullReferenceException:.ctor (string) emitted at 00000207FA8111F0 to 00000207FA811224 (code length 52) [SharpFlappyBird.exe]
converting method void System.StackOverflowException:.ctor (string)
Method void System.StackOverflowException:.ctor (string) emitted at 00000207FA811240 to 00000207FA811274 (code length 52) [SharpFlappyBird.exe]
```

**Comment by Pyrdacor** [comment]
I have the same problem with BassMidi while Bass itself works. I think the problem is, that BassMidi can't find Bass. I tried with the mentioned `DynamicLibrary` and it doesn't work. But adding `RtldGlobal ` (0x100) to `LoadLinux` did the trick. Maybe you can add it to managed bass and release a new nuget version?

Here the relevant change:

```cs
        const int RtldNow = 2;
        const int RtldGlobal = 256;

        [DllImport(LinuxDllName, EntryPoint = "dlopen")]
        static extern IntPtr LoadLinux(string FileName, int Flags = RtldNow | RtldGlobal);
```

**Comment by morphx666** [comment]
I was finally "able to fix the problem"... it appears that there was an architecture mismatch between the application and the BASS dll/so library being used.

To be honest, I could tell you for sure how that happened, but after forcing all projects to use x64, BASS started working just fine under linux... so... problem solved.

Thank you very much your time and support.
