### ISSUE TITLE
Issue resolving ManagedBass.Bass::ChannelSlideAttribute afgter upgrade to 3.0. (iOS)

### ISSUE THREAD

**Issue by vandenbrakel** [ManagedBass/ManagedBass#83]
Below code results in a build error on iOS. Any idea's?

```
public void FadeIn(int fadeInTime)
        {
            Bass.ChannelSlideAttribute(Stream, ChannelAttribute.Volume, 0, 1);
            Bass.ChannelSlideAttribute(Stream, ChannelAttribute.Volume, 1, fadeInTime);
        }

```

AppiOS/MTOUCH: Error MT2101: Can't resolve the reference 'System.Boolean ManagedBass.Bass::ChannelSlideAttribute(System.Int32,ManagedBass.ChannelAttribute,System.Single,System.Int32,System.Boolean)', referenced from the method 'System.Void MediaVibeMakeStuff.LibiOS.AudioPlayerCarbon.CarbonBassAudioPlayer::FadeOut(System.Int32)' in 'ManagedBass, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. (MT2101) (AppiOS)

Thanks.

**Comment by olitee** [comment]
This issue is caused by a versioning issue with the v3.0.0 packages. We're hoping to resolve this in the next few days with an updated release.
