### ISSUE TITLE
bass_fx ios

### ISSUE THREAD

**Issue by Chris1717** [ManagedBass/ManagedBass#91]
Hi,

I try to use bass and bass_fx on iOS with Xamarin. When I try to create a FX Stream the matching library can not be found 'bass_fx'. The library is linked static.

Any sugesstions?

**Comment by Chris1717** [comment]
I switched back to 2.0.4 and it works.

**Comment by olitee** [comment]
Hi @Chris1717 - this is very likely due to a known versioning issue with the v3.0.0 packages. We're hoping to fix in the next few days.
